### ISSUE TITLE
Problem with oauth-app example

### ISSUE THREAD

**Issue by wmuller64** [lightsparkdev/js-sdk#396]
When try to run the oauth-app example, i get this error:
[plugin:vite:import-analysis] Failed to resolve import "@lightsparkdev/ui/styles/global" from "src/index.tsx". Does the file exist?

In indext.tsx I change 'import { GlobalStyles } from "@lightsparkdev/ui/styles/global";' to 'import { GlobalStyles } from "@lightsparkdev/ui/src/styles/global";' as I see that is the right path.

Then the error changes in: 
[plugin:vite:import-analysis] Missing "./src/styles/global" specifier in "@lightsparkdev/ui" package

Am I missing something?

**Comment by coreymartin** [comment]
Hi @wmuller64 sorry about that - the build error should now be resolved. However oauth as a method of authentication with lightspark-sdk is deprecated for now and we're going to remove this example.

Instead we recommend API key authentication - the closest example we currently have on the web side of things would be the streaming-wallet-extension demo (see [this file](https://github.com/lightsparkdev/js-sdk/blob/main/apps/examples/streaming-wallet-extension/src/lightsparkClientProvider.tsx#L18) in particular). Our NodeJS scripts examples may also be helpful, see [this file](https://github.com/lightsparkdev/js-sdk/blob/main/apps/examples/nodejs-scripts/src/lightspark-sdk/getAccountDashboard.ts).
