### ISSUE TITLE
lightspark-sdk README example createInvoice error

### ISSUE THREAD

**Issue by FrankRSC** [lightsparkdev/js-sdk#403]
The example does not work, it gives me this error

LightsparkException [Error]: Request CreateInvoice failed. [{"message":"Variable '$node_id' got invalid value 10; Expected type 'ID'. The id input is not valid.","locations":[{"line":3,"column":5}],"extensions":{"error_name":"InvalidInputException"}},{"message":"Variable '$amount_msats' got invalid value 'Whasssupppp'; Expected type 'Long'. The input value must be an integer.","locations":[{"line":4,"column":5}],"extensions":{"error_name":"InvalidInputException"}}]

It is outdated?

**Comment by shreyav** [comment]
Sorry about that! Looks like the README was incorrect. Could you please try:

```
const encodedInvoice = await lightsparkClient.createInvoice({
  nodeId: RECEIVING_NODE_ID,
  amountMsats: 100000,
  memo: "Whasssupppp",
  type: InvoiceType.AMP,
});
```

**Comment by FrankRSC** [comment]
It didn't work that way, I made it work like this:
```
const encodedInvoice = await lightsparkClient.createInvoice(
RECEIVING_NODE_ID,
100000,
"Whasssupppp",
InvoiceType.AMP,
);
```
Thanks!
