### ISSUE TITLE
text-encoding dependency is no longer maintained

### ISSUE THREAD

**Issue by xavierraffin** [lightsparkdev/js-sdk#412]
The `text-encoding` package used by `@lightsparkdev/core` is deprecated from the own word of its maintainer.

See the mention on the npm project page: https://www.npmjs.com/package/text-encoding
The github repo has been archived and is not updated anymore: https://github.com/inexorabletash/text-encoding

This generates a warning message when `npm install`:

```
npm warn deprecated text-encoding@0.7.0: no longer maintained
```

This is true on the last released version `@lightsparkdev/lightspark-sdk@1.8.1`

Either @lightsparkdev forks text-encoding and maintain it or replace the dependency with something else.

**Comment by sayohnahilan** [comment]
I'm running into the same issue. Are there any plans to tackle this?

**Comment by pengying** [comment]
We've reviewed usage of the `text-encoding` dependency and found that it's no longer necessary.  We're working on a new release removing the dependency from package.json.

**Comment by coreymartin** [comment]
@xavierraffin @sayohnahilan This dependency has been removed and new package versions [published](https://github.com/lightsparkdev/js-sdk/pull/428): lightspark-sdk@1.8.6, lightspark-cli@0.0.60, core@1.2.4, crypto-wasm@0.1.7.
